### ISSUE TITLE
Issue with bs_pm

### ISSUE THREAD

**Issue by Gian77** [Guan06/mina#1]
Hello @Guan06 , 

thanks for the code! I am trying to run it on a data set but I was not able to get it to work. Please see below... Any suggestions?
Additionally, did you publish this package somewhere? I was not able to find a paper about it. Thanks a lot!

```
> physeq_kel_core
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 110 taxa and 546 samples ]
sample_data() Sample Data:       [ 546 samples by 9 sample variables ]
tax_table()   Taxonomy Table:    [ 110 taxa by 16 taxonomic ranks ]
refseq()      DNAStringSet:      [ 110 reference sequences ]

> tail(sort(sample_sums(physeq_kel_core), decreasing = TRUE))
   M2218x158U    M4210x158U    M1401x158U M3803x158UxLO    M3615x158U    M2614x158U 
         5433          5335          5329          4362          3560          2926 

> otu_table_kel_filt <-
+   as(physeq_kel_core@otu_table, "matrix") %>%
+   data.frame()

> dim(otu_table_kel_filt)
[1] 110 546

> class(otu_table_kel_filt)
[1] "data.frame"

> meta_kel <-
+   as(physeq_kel_core@sam_data, "data.frame")

> dim(meta_kel)
[1] 546  10

> class(meta_kel)
[1] "data.frame"

> mina_kel <- new("mina", tab = as.matrix(otu_table_kel_filt), des = meta_kel)

> str(mina_kel)
Formal class 'mina' [package "mina"] with 14 slots
  ..@ tab     : num [1:110, 1:546] 727 3278 38 60 8 ...
  .. ..- attr(*, "dimnames")=List of 2
  .. .. ..$ : chr [1:110] "OTU_31" "OTU_17" "OTU_56" "OTU_103" ...
  .. .. ..$ : chr [1:546] "M4412x212I" "M5817x212I" "M6016x212U" "M6608x286U" ...
  ..@ des     :'data.frame':	546 obs. of  10 variables:
  .. ..$ PLOT_GL       : chr [1:546] "M4412" "M5817" "M6016" "M6608" ...
  .. ..$ Date          : num [1:546] 212 212 212 286 233 260 212 212 212 260 ...
  .. ..$ site          : chr [1:546] "M" "M" "M" "M" ...
  .. ..$ inf           : chr [1:546] "I" "I" "U" "U" ...
  .. ..$ ident         : chr [1:546] "M4" "M5" "M6" "M6" ...
  .. ..$ PLANT_ID      : chr [1:546] "J024.A" "J258.A" "J522.B" "J607.A" ...
  .. ..$ Eco           : chr [1:546] "midwest" "midwest" "eastcoast" "eastcoast" ...
  .. ..$ Subpopulations: chr [1:546] "Midwest" "Midwest" "Atlantic" "Atlantic" ...
  .. ..$ is.neg        : logi [1:546] FALSE FALSE FALSE FALSE FALSE FALSE ...
  .. ..$ Time          : Factor w/ 5 levels "158","212","233",..: 2 2 2 5 3 4 2 2 2 4 ...
  ..@ norm    : NULL
  ..@ dis     : NULL
  ..@ dmr     : NULL
  ..@ adj     : NULL
  ..@ adj_sig : NULL
  ..@ cls     : NULL
  ..@ cls_tab : NULL
  ..@ multi   : NULL
  ..@ perm    : NULL
  ..@ dis_bs  : NULL
  ..@ dis_pm  : NULL
  ..@ dis_stat: NULL

> mina_kel <- norm_tab(mina_kel, method = "raref", depth = 2900) # rarefy samples

> mina_kel <- fit_tabs(mina_kel)
Error in `$<-.data.frame`(`*tmp*`, "Sample_ID", value = integer(0)) : 
  replacement has 0 rows, data has 546
```

I then tried also, just in case...

```
> mina_kel <- bs_pm(mina_kel, group = "Date", per = 0.5)
110 components are used for bs_pm before filtering.
0 samples are used for bs_pm before filtering.
0 groups with 0 samples used for bootstrap.
Error in .local(x, group, ...) : 
  Not enough samples for NA bootstrap after filtering!
```
I have 5 groups in this time series data set.

```
 > table(meta_kel$Date)
158 212 233 260 286 
 98 125 111 106 106 
```

**Comment by Guan06** [comment]
Hi, Thanks for trying this tool out ; )

Seems like your data frame where you store metadata doesn't really fit the format, could you please print the head of the meta_kel? For those details, you could find in vignette.

Unfortunately, the manuscript is still under preparation, so far, it is published as an R package in Bioconductor, so if you found it useful, you could also find it there.

Best,
Rui

**Comment by Guan06** [comment]
> Hello @Guan06 ,
> 
> thanks for the code! I am trying to run it on a data set but I was not able to get it to work. Please see below... Any suggestions? Additionally, did you publish this package somewhere? I was not able to find a paper about it. Thanks a lot!
> 
> ```
> > physeq_kel_core
> phyloseq-class experiment-level object
> otu_table()   OTU Table:         [ 110 taxa and 546 samples ]
> sample_data() Sample Data:       [ 546 samples by 9 sample variables ]
> tax_table()   Taxonomy Table:    [ 110 taxa by 16 taxonomic ranks ]
> refseq()      DNAStringSet:      [ 110 reference sequences ]
> 
> > tail(sort(sample_sums(physeq_kel_core), decreasing = TRUE))
>    M2218x158U    M4210x158U    M1401x158U M3803x158UxLO    M3615x158U    M2614x158U 
>          5433          5335          5329          4362          3560          2926 
> 
> > otu_table_kel_filt <-
> +   as(physeq_kel_core@otu_table, "matrix") %>%
> +   data.frame()
> 
> > dim(otu_table_kel_filt)
> [1] 110 546
> 
> > class(otu_table_kel_filt)
> [1] "data.frame"
> 
> > meta_kel <-
> +   as(physeq_kel_core@sam_data, "data.frame")
> 
> > dim(meta_kel)
> [1] 546  10
> 
> > class(meta_kel)
> [1] "data.frame"
> 
> > mina_kel <- new("mina", tab = as.matrix(otu_table_kel_filt), des = meta_kel)
> 
> > str(mina_kel)
> Formal class 'mina' [package "mina"] with 14 slots
>   ..@ tab     : num [1:110, 1:546] 727 3278 38 60 8 ...
>   .. ..- attr(*, "dimnames")=List of 2
>   .. .. ..$ : chr [1:110] "OTU_31" "OTU_17" "OTU_56" "OTU_103" ...
>   .. .. ..$ : chr [1:546] "M4412x212I" "M5817x212I" "M6016x212U" "M6608x286U" ...
>   ..@ des     :'data.frame':	546 obs. of  10 variables:
>   .. ..$ PLOT_GL       : chr [1:546] "M4412" "M5817" "M6016" "M6608" ...
>   .. ..$ Date          : num [1:546] 212 212 212 286 233 260 212 212 212 260 ...
>   .. ..$ site          : chr [1:546] "M" "M" "M" "M" ...
>   .. ..$ inf           : chr [1:546] "I" "I" "U" "U" ...
>   .. ..$ ident         : chr [1:546] "M4" "M5" "M6" "M6" ...
>   .. ..$ PLANT_ID      : chr [1:546] "J024.A" "J258.A" "J522.B" "J607.A" ...
>   .. ..$ Eco           : chr [1:546] "midwest" "midwest" "eastcoast" "eastcoast" ...
>   .. ..$ Subpopulations: chr [1:546] "Midwest" "Midwest" "Atlantic" "Atlantic" ...
>   .. ..$ is.neg        : logi [1:546] FALSE FALSE FALSE FALSE FALSE FALSE ...
>   .. ..$ Time          : Factor w/ 5 levels "158","212","233",..: 2 2 2 5 3 4 2 2 2 4 ...
>   ..@ norm    : NULL
>   ..@ dis     : NULL
>   ..@ dmr     : NULL
>   ..@ adj     : NULL
>   ..@ adj_sig : NULL
>   ..@ cls     : NULL
>   ..@ cls_tab : NULL
>   ..@ multi   : NULL
>   ..@ perm    : NULL
>   ..@ dis_bs  : NULL
>   ..@ dis_pm  : NULL
>   ..@ dis_stat: NULL
> 
> > mina_kel <- norm_tab(mina_kel, method = "raref", depth = 2900) # rarefy samples
> 
> > mina_kel <- fit_tabs(mina_kel)
> Error in `$<-.data.frame`(`*tmp*`, "Sample_ID", value = integer(0)) : 
>   replacement has 0 rows, data has 546
> ```
> 
> I then tried also, just in case...
> 
> ```
> > mina_kel <- bs_pm(mina_kel, group = "Date", per = 0.5)
> 110 components are used for bs_pm before filtering.
> 0 samples are used for bs_pm before filtering.
> 0 groups with 0 samples used for bootstrap.
> Error in .local(x, group, ...) : 
>   Not enough samples for NA bootstrap after filtering!
> ```
> 
> I have 5 groups in this time series data set.
> 
> ```
>  > table(meta_kel$Date)
> 158 212 233 260 286 
>  98 125 111 106 106 
> ```

Hi, Thanks for trying this tool out ; )

Seems like your data frame where you store metadata doesn't really fit the format, could you please print the head of the meta_kel? For those details, you could find in vignette.

Unfortunately, the manuscript is still under preparation, so far, it is published as an R package in Bioconductor, so if you found it useful, you could also find it there.

Best,
Rui

**Comment by Gian77** [comment]
Hello @Guan06,

Thank you for the incredibility fast answer, I appreciate that.

Here a shot of the data frames

```
> otu_table_kel_filt[1:6, 1:10]
        M4412x212I M5817x212I M6016x212U M6608x286U M6608x233U M5804x260I M6711x212U M4617x212U M1202x212I M4021x260I
OTU_31         727         55        234         20         26        191        175        642         67        230
OTU_17        3278        221       1363        127        397       2111        519       3867        207        817
OTU_56          38        260          0        160        113          6         87         33         10          7
OTU_103         60        539         21        578         30         18         48        970         42        166
OTU_92           8          0        392          6        102         53         11          5         14         18
OTU_2         2530       4231       2953       3667       3577       2950       9617       6456       4890       6349

> head(meta_kel)
           PLOT_GL Date site inf ident PLANT_ID       Eco Subpopulations is.neg Time
M4412x212I   M4412  212    M   I    M4   J024.A   midwest        Midwest  FALSE  212
M5817x212I   M5817  212    M   I    M5   J258.A   midwest        Midwest  FALSE  212
M6016x212U   M6016  212    M   U    M6   J522.B eastcoast       Atlantic  FALSE  212
M6608x286U   M6608  286    M   U    M6   J607.A eastcoast       Atlantic  FALSE  286
M6608x233U   M6608  233    M   U    M6   J607.A eastcoast       Atlantic  FALSE  233
M5804x260I   M5804  260    M   I    M5   J419.A     Texas           Gulf  FALSE  260

> str(meta_kel)
'data.frame':	546 obs. of  10 variables:
 $ PLOT_GL       : chr  "M4412" "M5817" "M6016" "M6608" ...
 $ Date          : num  212 212 212 286 233 260 212 212 212 260 ...
 $ site          : chr  "M" "M" "M" "M" ...
 $ inf           : chr  "I" "I" "U" "U" ...
 $ ident         : chr  "M4" "M5" "M6" "M6" ...
 $ PLANT_ID      : chr  "J024.A" "J258.A" "J522.B" "J607.A" ...
 $ Eco           : chr  "midwest" "midwest" "eastcoast" "eastcoast" ...
 $ Subpopulations: chr  "Midwest" "Midwest" "Atlantic" "Atlantic" ...
 $ is.neg        : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ Time          : Factor w/ 5 levels "158","212","233",..: 2 2 2 5 3 4 2 2 2 4 ...

```
Thanks!
G.

**Comment by Guan06** [comment]
> Hello @Guan06,
> 
> Thank you for the incredibility fast answer, I appreciate that.
> 
> Here a shot of the data frames
> 
> ```
> > otu_table_kel_filt[1:6, 1:10]
>         M4412x212I M5817x212I M6016x212U M6608x286U M6608x233U M5804x260I M6711x212U M4617x212U M1202x212I M4021x260I
> OTU_31         727         55        234         20         26        191        175        642         67        230
> OTU_17        3278        221       1363        127        397       2111        519       3867        207        817
> OTU_56          38        260          0        160        113          6         87         33         10          7
> OTU_103         60        539         21        578         30         18         48        970         42        166
> OTU_92           8          0        392          6        102         53         11          5         14         18
> OTU_2         2530       4231       2953       3667       3577       2950       9617       6456       4890       6349
> 
> > head(meta_kel)
>            PLOT_GL Date site inf ident PLANT_ID       Eco Subpopulations is.neg Time
> M4412x212I   M4412  212    M   I    M4   J024.A   midwest        Midwest  FALSE  212
> M5817x212I   M5817  212    M   I    M5   J258.A   midwest        Midwest  FALSE  212
> M6016x212U   M6016  212    M   U    M6   J522.B eastcoast       Atlantic  FALSE  212
> M6608x286U   M6608  286    M   U    M6   J607.A eastcoast       Atlantic  FALSE  286
> M6608x233U   M6608  233    M   U    M6   J607.A eastcoast       Atlantic  FALSE  233
> M5804x260I   M5804  260    M   I    M5   J419.A     Texas           Gulf  FALSE  260
> 
> > str(meta_kel)
> 'data.frame':	546 obs. of  10 variables:
>  $ PLOT_GL       : chr  "M4412" "M5817" "M6016" "M6608" ...
>  $ Date          : num  212 212 212 286 233 260 212 212 212 260 ...
>  $ site          : chr  "M" "M" "M" "M" ...
>  $ inf           : chr  "I" "I" "U" "U" ...
>  $ ident         : chr  "M4" "M5" "M6" "M6" ...
>  $ PLANT_ID      : chr  "J024.A" "J258.A" "J522.B" "J607.A" ...
>  $ Eco           : chr  "midwest" "midwest" "eastcoast" "eastcoast" ...
>  $ Subpopulations: chr  "Midwest" "Midwest" "Atlantic" "Atlantic" ...
>  $ is.neg        : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...
>  $ Time          : Factor w/ 5 levels "158","212","233",..: 2 2 2 5 3 4 2 2 2 4 ...
> ```
> 
> Thanks! G.

Hi G.,

I think you need a column called "Sample_ID" in your meta_kel data frame, the function cannot take row names automatically. You could find the details here https://bioconductor.org/packages/release/bioc/vignettes/mina/inst/doc/mina.html 

Let me know if this doesn't resolve your problem.

Best,
Rui

**Comment by Gian77** [comment]
@Guan06,

Sorry! I thought the function was able to generate that column, maybe I missed that part. With the column in, I was able to run through (please see below). One question, in `dis_stat` there is a column called `Compare`, why I only see the comparison of two groups there? I have 5 groups (networks, `158 212 233 260 286`) I would like to compare, but I only see the comparisons between the same, last, one `286_286`. What am I missing? You showed a table here https://github.com/Guan06/mina I am not really sure how to extrapolate it, any help? 
If it is hard to explain and you would like to chat privately I would happy too. Thanks again!

G.

```
> mina_kel <- new("mina", tab = as.matrix(otu_table_kel_filt), des = meta_kel)

> head(mina_kel@des)
   Sample_ID PLOT_GL Date site inf ident PLANT_ID       Eco Subpopulations is.neg
1 M4412x212I   M4412  212    M   I    M4   J024.A   midwest        Midwest  FALSE
2 M5817x212I   M5817  212    M   I    M5   J258.A   midwest        Midwest  FALSE
3 M6016x212U   M6016  212    M   U    M6   J522.B eastcoast       Atlantic  FALSE
4 M6608x286U   M6608  286    M   U    M6   J607.A eastcoast       Atlantic  FALSE
5 M6608x233U   M6608  233    M   U    M6   J607.A eastcoast       Atlantic  FALSE
6 M5804x260I   M5804  260    M   I    M5   J419.A     Texas           Gulf  FALSE
> mina_kel <- norm_tab(mina_kel, method = "raref", depth = 2900) # rarefy samples
> mina_kel <- bs_pm(mina_kel, group = "Date", per = 0.05)
110 components are used for bs_pm before filtering.
546 samples are used for bs_pm before filtering.
5 groups with 546 samples used for bootstrap.

> mina_kel <- fit_tabs(mina_kel)

> mina_kel <- net_dis(mina_kel, method = "Jaccard")

> head(dis_stat(mina_kel))
  Compare Distance_Mean Distance_SD Distance_PM_Mean Distance_PM_SD    N         p    Group1    Group2
1 286_286     0.5564692  0.04599506        0.5531981     0.04685492 1296 0.4502699 0.5061259 0.6629844
2 286_286     0.5564692  0.04599506        0.5531981     0.04685492 1296 0.4502699 0.5061259 0.5262851
3 286_286     0.5564692  0.04599506        0.5531981     0.04685492 1296 0.4502699 0.5061259 0.5592253
4 286_286     0.5564692  0.04599506        0.5531981     0.04685492 1296 0.4502699 0.5061259 0.5813226
5 286_286     0.5564692  0.04599506        0.5531981     0.04685492 1296 0.4502699 0.5061259 0.5805254
6 286_286     0.5564692  0.04599506        0.5531981     0.04685492 1296 0.4502699 0.5061259 0.5976312

dist_kel<-
  as_tibble(
  dis_stat(mina_kel))

table(dist_kel$Compare)

286_286 
   1296 
```

**Comment by Guan06** [comment]
> @Guan06,
> 
> Sorry! I thought the function was able to generate that column, maybe I missed that part. With the column in, I was able to run through (please see below). One question, in `dis_stat` there is a column called `Compare`, why I only see the comparison of two groups there? I have 5 groups (networks, `158 212 233 260 286`) I would like to compare, but I only see the comparisons between the same, last, one `286_286`. What am I missing? You showed a table here https://github.com/Guan06/mina I am not really sure how to extrapolate it, any help? If it is hard to explain and you would like to chat privately I would happy too. Thanks again!
> 
> G.
> 
> ```
> > mina_kel <- new("mina", tab = as.matrix(otu_table_kel_filt), des = meta_kel)
> 
> > head(mina_kel@des)
>    Sample_ID PLOT_GL Date site inf ident PLANT_ID       Eco Subpopulations is.neg
> 1 M4412x212I   M4412  212    M   I    M4   J024.A   midwest        Midwest  FALSE
> 2 M5817x212I   M5817  212    M   I    M5   J258.A   midwest        Midwest  FALSE
> 3 M6016x212U   M6016  212    M   U    M6   J522.B eastcoast       Atlantic  FALSE
> 4 M6608x286U   M6608  286    M   U    M6   J607.A eastcoast       Atlantic  FALSE
> 5 M6608x233U   M6608  233    M   U    M6   J607.A eastcoast       Atlantic  FALSE
> 6 M5804x260I   M5804  260    M   I    M5   J419.A     Texas           Gulf  FALSE
> > mina_kel <- norm_tab(mina_kel, method = "raref", depth = 2900) # rarefy samples
> > mina_kel <- bs_pm(mina_kel, group = "Date", per = 0.05)
> 110 components are used for bs_pm before filtering.
> 546 samples are used for bs_pm before filtering.
> 5 groups with 546 samples used for bootstrap.
> 
> > mina_kel <- fit_tabs(mina_kel)
> 
> > mina_kel <- net_dis(mina_kel, method = "Jaccard")
> 
> > head(dis_stat(mina_kel))
>   Compare Distance_Mean Distance_SD Distance_PM_Mean Distance_PM_SD    N         p    Group1    Group2
> 1 286_286     0.5564692  0.04599506        0.5531981     0.04685492 1296 0.4502699 0.5061259 0.6629844
> 2 286_286     0.5564692  0.04599506        0.5531981     0.04685492 1296 0.4502699 0.5061259 0.5262851
> 3 286_286     0.5564692  0.04599506        0.5531981     0.04685492 1296 0.4502699 0.5061259 0.5592253
> 4 286_286     0.5564692  0.04599506        0.5531981     0.04685492 1296 0.4502699 0.5061259 0.5813226
> 5 286_286     0.5564692  0.04599506        0.5531981     0.04685492 1296 0.4502699 0.5061259 0.5805254
> 6 286_286     0.5564692  0.04599506        0.5531981     0.04685492 1296 0.4502699 0.5061259 0.5976312
> 
> dist_kel<-
>   as_tibble(
>   dis_stat(mina_kel))
> 
> table(dist_kel$Compare)
> 
> 286_286 
>    1296 
> ```

Thanks a lot for pointing this out! I think this actually is a bug in the code, I will fix it and let you know. I would also be happy to give suggestions about other functions in the package if you would like to chat privately. 

Best,
Rui

**Comment by Gian77** [comment]
Thanks @Guan06,
Please let me know when it's fixed and yes, let's chat.
G.

**Comment by Guan06** [comment]
> Thanks @Guan06, Please let me know when it's fixed and yes, let's chat. G.

Hi,

I just fixed the bug here tested from my sie, you may need to re-install the package (from Github) and re-run the scripts.  Some extra lines got copied in the statistics function accidentally in one of the versions and were kept until now... Let me know if it is not working.

Thanks!

Best,
Rui

**Comment by Gian77** [comment]
Thanks @Guan06,

I think it worked. It generated comparisons as you can see
```
# A tibble: 5 × 6
  DOY1   `158`     `212`     `233`     `260`    `286`
  <chr>  <dbl>     <dbl>     <dbl>     <dbl>    <dbl>
1 158    0.741  0.000771  0.000771  0.000771 0.000771
2 212   NA      0.431     0.0254    0.000771 0.000771
3 233   NA     NA         0.574     0.0146   0.000771
4 260   NA     NA        NA         0.588    0.0254  
5 286   NA     NA        NA        NA        0.578  
```
I would be really happy to chat about how these comparisons are generated. You can reach me here gian[dot]benucci[at]gmail[dot]com 
Thanks again!
G.

**Comment by Guan06** [comment]
Hi, I will close this issue then, thanks for getting in touch ; )
